spring:
  datasource:
    username: postgres
    password: Enter5510
    url: jdbc:postgresql://localhost:5432/OnlineQueue
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: main
  mustache:
    check-template-location: false
  cloud:
    openfeign:
      client:
        config:
          jwt-client:
            url: http://localhost:8084/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
server:
  port: 8083

#logging:
#  level:
#    root: DEBUG
